version: "3.7"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    environment:
      - PORT=3001
      - DB_DATABASE=test
    command: npm run test
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    command: npm run test
  postgres:
    image: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
